# Configuration pour Render avec Railway DB
services:
  - type: web
    name: appwoyofal
    env: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: yamabiko.proxy.rlwy.net
      - key: DB_PORT
        value: "33405"
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: piwMpVaBZIIcOyltuWqYmYHSsgGmiTTp
